stages:
  - test
  - build
  - docker

variables:
  DOCKER_IMAGE: bastienfaucher/booking-service
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Étape 1 : Tests
test:
  stage: test
  image: gradle:7.6-jdk17
  script:
    - ./gradlew test

# Étape 2 : Build JAR
build:
  stage: build
  image: gradle:7.6-jdk17
  script:
    - ./gradlew clean build

# Étape 3 : Docker build & push
docker:
  stage: docker
  image: docker:24.0.2
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main