version: '3.8'

services:

  booking-db:
    image: mysql:8
    container_name: booking-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booking_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-password"]
      interval: 10s
      timeout: 5s
      retries: 5

  booking-service:
    image: bastienfaucher/booking-service
    container_name: booking-service
    ports:
      - "8080:8080"
    depends_on:
      booking-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://booking-db:3306/booking_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=8080