spring:
  application:
    name: booking-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      max-lifetime: 300000      # 5 minutes en ms
      keepalive-time: 60000

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: booking-service

customer-service:
  url: http://customer-service:8084

themeparkride-service:
  url: http://themeparkride-service:8082