apiVersion: v1
kind: Service
metadata:
  name: booking-db
  namespace: dev
spec:
  selector:
    app: booking-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
