# Secret pour le mot de passe de la base de données
apiVersion: v1
kind: Secret
metadata:
  name: booking-secrets
  namespace: dev
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "cGFzc3dvcmRfYm9va2luZw=="  # "password_booking" encodé en base64
